site_name: Vayner Quality Assessments Libary Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - QAFunctions: QAFunctions.md
  - Other Vayner Libraries: OtherVaynerLibraries.md